
package mx.uv.consumo.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "inventarioPort", targetNamespace = "https://inventario.mx.uv/inventario")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventarioPort {


    /**
     * 
     * @param verificarProductoRequest
     * @return
     *     returns mx.uv.consumo.wsdl.VerificarProductoResponse
     */
    @WebMethod(operationName = "VerificarProducto")
    @WebResult(name = "VerificarProductoResponse", targetNamespace = "https://inventario.mx.uv/inventario", partName = "VerificarProductoResponse")
    public VerificarProductoResponse verificarProducto(
        @WebParam(name = "VerificarProductoRequest", targetNamespace = "https://inventario.mx.uv/inventario", partName = "VerificarProductoRequest")
        VerificarProductoRequest verificarProductoRequest);

    /**
     * 
     * @param agregarProductoRequest
     * @return
     *     returns mx.uv.consumo.wsdl.AgregarProductoResponse
     */
    @WebMethod(operationName = "AgregarProducto")
    @WebResult(name = "AgregarProductoResponse", targetNamespace = "https://inventario.mx.uv/inventario", partName = "AgregarProductoResponse")
    public AgregarProductoResponse agregarProducto(
        @WebParam(name = "AgregarProductoRequest", targetNamespace = "https://inventario.mx.uv/inventario", partName = "AgregarProductoRequest")
        AgregarProductoRequest agregarProductoRequest);

}
